FROM jekyll_base

ENV PROJECT_DIR=/project
RUN mkdir /project && chown jekyll /project
VOLUME /project

COPY --chown=jekyll:jekyll ["Gemfile", "Gemfile.lock", "/project/"]
RUN gosu jekyll make dependencies
COPY --chown=jekyll:jekyll [".", "/project/"]

CMD make jekyll/serve
