version: '3.2'
services:
  base:
    build:
      context: .
      dockerfile: "$PWD/Dockerfile.base"
      args:
        JEKYLL_USER: developer
  project:
    build:
      context: "${PROJECT_DIR:-..}"
      dockerfile: "$PWD/Dockerfile.project"
    depends_on:
      - base
    ports:
      - 4000:4000
    volumes:
      - type: bind
        source: "${PROJECT_DIR:-..}"
        target: '/project'
